skip_tags: true

configuration: Release

before_build:
  - nuget restore src\ObservablePropertyChanged.sln

build:
  parallel: true
  project: src\ObservablePropertyChanged.sln
  verbosity: minimal

artifacts:
  - path: src\artifacts\*.nupkg