configuration: Release

before_build:
  - nuget restore src\ObservablePropertyChanged.sln

build:
  parallel: true
  project: src\ObservablePropertyChanged.sln
  verbosity: minimal

cache:
  - packages -> **\packages.config

artifacts:
  - path: src\artifacts\*.nupkg